name: Generate GitHub Snake SVG
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'  # optional: daily at 02:00 UTC

permissions:
  contents: write  # allow job to push back to repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Create output dir
        run: mkdir -p output

      - name: Generate snake SVG (placeholder)
        run: python scripts/generate_snake.py output/github-snake.svg

      - name: Commit generated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake.svg || true
          git commit -m "chore: update github-snake.svg" || echo "no changes to commit"
          git push
