name: GitHub Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"     # daily at midnight UTC (adjust if you want)
  workflow_dispatch:        # allow manual run
  push:
    branches:
      - main

# allow action to create / update branches and publish
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub contributions snake animations
        uses: Platane/snk@v3
        with:
          # username to generate the animation for; repo owner works for profile repos
          github_user_name: ${{ github.repository_owner }}
          # outputs to generate: svg for light/dark and an optional gif
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy generated files to 'output' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "chore: update snake animation [skip ci]"
